image: alpine/edge
packages:
  - openssh-client
  - python3
  - py3-pip
sources:
  - https://git.sr.ht/~ajhalili2006/tildeweb
secrets:
  - b4ffc5fb-bc8c-4e89-b38a-48b56155a443
triggers:
  - action: email
    condition: always
    to: ~ajhalili2006/public-inbox@lists.sr.ht
    cc: ajhalili2006@gmail.com
tasks:
  - build: |
      cd tildeweb && pip3 install -r requirements.txt
      mkdocs build -d public -f mkdocs.yml && mkdocs build -d public_ctrl-c -f mkdocs.ctrl-c.yml
  - deploy: |
      cd tildeweb
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      eval $(ssh-agent) && ssh-add ~/.ssh/passwordless-auth-sshfs
      rsync -rP public ajhalili2006@vern.cc:/home/ajhalili2006/public_html/
      rsync -rP public_ctrl-c ajhalili2006@ctrl-c.club:/home/ajhalili2006/public_html/
      #rsync -rP gmi ajhalili2006@vern.cc:/home/ajhalili2006/public_gemini/
      #rsync -rP gmi ajhalili2006@ctrl-c.club:/home/ajhalili2006/public_gemini/
