image: alpine/edge
environment: 
  FF_ENABLE_COMMIT_DATA: "true"
  FF_GENERATE_SOCIAL_CARDS: "true"
packages:
  - openssh-client
  - python3
  - py3-pip
  - py3-wheel
  - py3-setuptools
  - cairo-dev
  - freetype-dev
  - libffi-dev
  - jpeg-dev
  - libpng-dev
  - zlib-dev
sources:
  - https://git.sr.ht/~ajhalili2006/web
secrets:
  - b4ffc5fb-bc8c-4e89-b38a-48b56155a443
triggers:
  - action: email
    condition: always
    to: ~ajhalili2006/public-inbox@lists.sr.ht
    cc: ajhalili2006@gmail.com
tasks:
  # in case of triggered from hottub
  - repo-sync: |
      cd tildeweb
  - build: |
      sudo rm /usr/lib/python3*/EXTERNALLY_MANAGED -rfv || true
      cd tildeweb && pip3 install -r requirements.txt --user
      export PATH="$PATH:$HOME/.local/bin"
      bash ./build.sh
  - generate-archive: |
      cd tildeweb
      tar -C public -cvz . -f tildeweb-prod-build.tar.gz
  - deploy: |
      cd tildeweb
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      rsync -rP -e 'ssh -i ~/.ssh/passwordless-auth-sshfs' public/ ajhalili2006@p.projectsegfau.lt:/home/ajhalili2006/public_html
      rsync -rP -e 'ssh -i ~/.ssh/passwordless-auth-sshfs' public/ ajhalili2006@ctrl-c.club:/home/ajhalili2006/public_html
artifacts:
  - tildeweb/tildeweb-prod-build.tar.gz
