image:
  name: dock.mau.dev/ajhalili2006/tildeverse-web/build-ci
  entrypoint:
    - sh

variables:
  FF_ENABLE_COMMIT_DATA: "true"
  FF_GENERATE_SOCIAL_CARDS: "true"
  SECURE_FILES_DOWNLOAD_PATH: /run/secrets

.setupkit:
  before_script:
    - apk add curl gnupg bash coreutils
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sh
  tags:
    - amd64

stages:
  - build
  - lint
  - deploy

build:main:
  extends: [ .setupkit ]
  stage: build
  script:
    - bash ./build.sh
  artifacts:
    paths:
      - public
    untracked: false
    when: on_success
    expire_in: "21 days"
  cache:
    paths:
      - .cache
      - .venv
    key: pages-build-main
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      changes:
        - mkdocs.yml
        - markdown/*
        - markdown/**/*
        - .gitlab-ci.yml
        - docker/Dockerfile
        - package*.json
        - .trigger-deploy

deploy:main:
  stage: deploy
  extends: [ .setupkit ]
  needs:
    - build:main
  script:
    - apk add nodejs-lts npm && npm i
    - ls -Al
    - doppler run -- echo hi
  cache:
    paths:
      - node_modules
    key: deploykit-main
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      changes:
        - mkdocs.yml
        - markdown/*
        - markdown/**/*
        - .gitlab-ci.yml
        - docker/Dockerfile
        - package*.json
        - .trigger-deploy
