
checkoutLocation: ajhalili2006/website

image: quay.io/ajhalili2006/mkdocs-material-build-ci:commit-8637138aeba0b34174605c7688a65440b7d0b2ec

tasks:
  - init: |
      pipenv --python 3.12 sync --verbose
    command: |
      FF_ENABLE_COMMIT_DATA=true pipenv run -- mkdocs serve --watch overrides --watch-theme --livereload
    name: site-localdev
    env:
      FF_ENABLE_COMMIT_DATA: "true" # Required to use git-revision-date-localized, like in prod.

ports:
  - port: 8000
    onOpen: notify
    visibility: public

vscode:
  extensions:
    - foam.foam-vscode
    - DavidAnson.vscode-markdownlint
    - timonwong.shellcheck
    - ms-azuretools.vscode-docker
    - vivaxy.vscode-conventional-commits
    - akosyakov.gitpod-monitor
