# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    #nodejs: 18
  jobs:
    post_build:
      - cp -rv markdown/.well-known $READTHEDOCS_OUTPUT/html/.well-known
  apt_packages:
    - libcairo2-dev
    - libfreetype6-dev
    - libffi-dev
    - libjpeg-dev
    - libpng-dev
    - libz-dev
    - pngquant

mkdocs:
  configuration: mkdocs.readthedocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
  - requirements: requirements.txt
