# This is the root configuration for my personal website and also the default
# for userpage at ~vern.

# basics
site_name: ~ajhalili2006
site_url: https://andreijiroh.eu.org/
site_dir: public
site_author: Andrei Jiroh Halili
copyright: >
  Copyright &copy; 2022-present - Andrei Jiroh Halili and contributors, licensed under the
  <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a> license.
docs_dir: markdown
use_directory_urls: true

# repos
repo_url: https://mau.dev/ajhalili2006/tildeverse-web
edit_uri: edit/main/markdown
repo_name: source code

# navbar
nav:
  - Main Hub: 
    - index.md
    - nowpage: now.md
    - Contact: contact.md
    - "All my links": "https://ajhalili2006.start.page"
  - Personal user manual:
    - Manual Homepage: user-manual/index.md
    - Resume: user-manual/resume.md
    - DNI List: user-manual/dni.md
    - Boundaries: user-manual/boundaries.md
    - Communications: user-manual/communications.md
    - Keys: keys/index.md
    - Encrypted communications and keys: keys/index.md
  - Portfolio: 
    - portfolio/index.md
    - Projects: portfolio/projects.md
    - Communities: portfolio/communities.md
    - Tildes: portfolio/tildes.md
  - Blog: "https://blog.andreijiroh.eu.org" # todo: point to substack

# theme settings
theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.png
  icon:
    logo: octicons/person-16
    repo: material/gitlab
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# plugins
plugins:
  - social:
      cards: !ENV [FF_GENERATE_SOCIAL_CARDS, false]
  - search
  - redirects:
      redirect_maps:
        "user-manual/portfolio.md": "portfolio/index.md"
        "dni.md": "user-manual/dni.md"
        "resume.md": "user-manual/resume.md"
        "blog.md": "https://ajhalili2006.substack.com"
        "socials.md": "https://ajhalili2006.start.page"
        "communities.md": "portfolio/communities.md"
        "tildes.md": "portfolio/tildes.md"
        "projects.md": "portfolio/projects.md"
  # debugging/bug reporting purposes only, proceed with caution
  #- info
  - git-revision-date-localized:
      enabled: !ENV [FF_ENABLE_COMMIT_DATA, false]
      fallback_to_build_date: true
      enable_creation_date: true
  # TODO: Get Insiders for contributors and authors

# makrdown extensions
markdown_extensions:
  - toc:
      permalink: true
      title: On this page
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
  - md_in_html
  - admonition
  - abbr
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

# extras
extra:
  #deployment: staging
  # my socials
  social:
    - icon: simple/substack
      link: https://ajhalili2006.substack.com
      name: ~ajhalili2006's personal substack
    - icon: fontawesome/brands/mastodon
      link: https://tilde.zone/@ajhalili2006
      name: ~ajhalili2006 on tildeverse
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ajhalili2006
      name: ~ajhalili2006 on twitter, under his old username
    - icon: fontawesome/brands/github
      link: https://github.com/ajhalili2006
      name: ~ajhalili2006 on github
    - icon: fontawesome/brands/gitlab
      link: https://mau.dev/ajhalili2006
      name: ~ajhalili2006 on mauinum gitLab instance
    - icon: fontawesome/brands/git-alt
      link: https://sr.ht/~ajhalili2006
      name: ~ajhalili2006 on sr.ht
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/ajhalili2006
      name: ~ajhalili2006's personal (slash professional profile) facebook account
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ajhalili2006
      name: ~ajhalili2006 on linkedin for employers
  analytics:
    provider: plausible
    property: andreijiroh.eu.org
    url: "https://analytics.projectsegfau.lt"